name = "MatrixProtocolClient"
uuid = "dce90aba-d33e-11e8-1366-8bb55bd2702d"
authors = ["Adam Beckmeyer <adam_gpg@thebeckmeyers.xyz>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
